apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: go-sample-app
spec:
  builder:
    name: paketo-builder
    kind: Builder
  serviceAccount: build-bot
  #cacheSize: "1.5Gi"
  source:
    git:
      url: https://github.com/springone-tour-2020-cicd/go-sample-app
      revision: master
  tag: springone-tour-2020-cicd/go-sample-app:kpack-0.0.1
